sudo: required

services:
  - docker

language: go

go:
- 1.9.4

after_success:
  - env GOOS=linux GOARCH=386 go build
  - echo $(DOCKER_PASS) | docker login -u "$(DOCKER_USER)" --password-stdin
  - export REPO=sophos/httpmq
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO